package com.bldj.lexiang.commons;

public class Constant {

	/**
	 * 微信appid,appsecret
	 */
	public static String appID = "wx91da119751fdde4a";
	public static String appSecret = "4ae149de66a81bca8ef0e2986bf03792";
	
    /**
     * 超时时间
     */
    public static final int TIMEOUT = 10000;

    private static final int GD_LOG_LEVEL_INFO = 3;

    private static final int GD_LOG_LEVEL_NONE = 0;
    
    public static final String FILE_NAME = "bldj";
    
    public static final String LOCATION = "com.bldj.lexiang.location";

    /**
     * Set this flag to GD_LOG_LEVEL_NONE when releasing your application in
     * order to remove all logs generated by GreenDroid.
     */
    private static final int GD_LOG_LEVEL = GD_LOG_LEVEL_NONE;

    /**
     * Indicates whether info logs are enabled. This should be true only when
     * developing/debugging an application/the library
     */
    public static final boolean GD_INFO_LOGS_ENABLED = (GD_LOG_LEVEL == GD_LOG_LEVEL_INFO);
    
    public static final String  IMAGELOADER_LOCAL_TITLE = "file://";
    
	/**
	 * 我的头像保存目录
	 */
	public static String MyAvatarDir = "/sdcard/com.bldj.lexiang/head/";
    
}